### ISSUE TITLE
Could not build with babel@7 without sourcemap

### ISSUE THREAD

**Issue by JounQin** [ecomfe/san-loader#11]
When `devtool` is not enabled, webpack will throw an error like following:

```
ERROR in ./node_modules/babel-loader/lib!./node_modules/san-loader/lib/selector.js?type=script&index=0!./src/views/Home.san
Module build failed: Error: .inputSourceMap must be a boolean, object, or undefined
    at assertInputSourceMap (/local/GitHub/san-study/node_modules/@babel/core/lib/config/validation/option-assertions.js:43:11)
    at /local/GitHub/san-study/node_modules/@babel/core/lib/config/validation/options.js:83:20
    at Array.forEach (<anonymous>)
    at validate (/local/GitHub/san-study/node_modules/@babel/core/lib/config/validation/options.js:61:21)
    at loadConfig (/local/GitHub/san-study/node_modules/@babel/core/lib/config/index.js:37:48)
    at transformSync (/local/GitHub/san-study/node_modules/@babel/core/lib/transform-sync.js:13:36)
    at Object.transform (/local/GitHub/san-study/node_modules/@babel/core/lib/transform.js:20:65)
    at transpile (/local/GitHub/san-study/node_modules/babel-loader/lib/index.js:55:20)
    at Object.module.exports (/local/GitHub/san-study/node_modules/babel-loader/lib/index.js:179:20)
 @ ./src/views/Home.san 5:17-119
 @ ./src/router/index.js
 @ ./src/index.js
```

Reproduction: https://github.com/JounQin/san-study/blob/master/webpack.config.babel.js
Step:
1. Run `yarn && yarn build`, it works with sourcemap.
2. Then remove `devtool` option in webpack config, rerun `yarn build` you will get the error in console.

**Comment by JounQin** [comment]
Seems it's not maintaining at all.
